# Generated by Django 5.2.7 on 2025-11-15 08:46

import django.db.models.deletion
import django.utils.timezone
import payments.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text="Enter a descriptive name for the coupon (e.g., 'New Year Discount').", max_length=100)),
                ('code', models.CharField(help_text="Enter a unique code users will apply at checkout (e.g., 'NEWYEAR2026').", max_length=50, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, help_text='Enter the discount percentage (e.g., 10', max_digits=5)),
                ('startdate', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the coupon becomes active.')),
                ('enddate', models.DateTimeField(blank=True, help_text='The date and time when the coupon expires. Leave blank for no expiry.', null=True)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, help_text='Package display name', max_length=100, null=True)),
                ('tokens', models.PositiveIntegerField(help_text='Number of tokens included in this package')),
                ('description', models.TextField(blank=True, help_text='Short note about what this package offers', null=True)),
                ('currency', models.CharField(default='$', help_text='Currency symbol, e.g., $ or ₹', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for sorting packages')),
                ('is_popular', models.BooleanField(default=False, help_text='Mark if this is a popular package')),
                ('image', models.ImageField(blank=True, null=True, upload_to=payments.models.package_image_upload_path)),
            ],
            options={
                'db_table': 'packages',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'package_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('currency', models.CharField(default='$', help_text='Currency symbol, e.g., $ or ₹', max_length=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount for the entire order', max_digits=10)),
                ('coupon', models.CharField(blank=True, help_text='Applied coupon code', max_length=50, null=True)),
                ('gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST amount (18%) for the order', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount for the order including GST', max_digits=10)),
                ('tokens', models.PositiveIntegerField(default=0, help_text='Total tokens this order will credit to the user')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refund', 'Refund')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('currency', models.CharField(default='$', help_text='Currency symbol, e.g., $ or ₹', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tokens', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.order')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='payments.package')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='packagetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='payments.packagetype'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('response', models.JSONField(blank=True, help_text='Raw response from the payment gateway', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='payments.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
