# Generated by Django 5.2.7 on 2025-12-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referral',
            field=models.CharField(blank=True, help_text='Applied referral code', max_length=12, null=True),
        ),
    ]
