# Generated by Django 5.2.7 on 2026-04-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Full name (e.g. US Dollar).', max_length=100)),
                ('code', models.CharField(help_text='ISO code (e.g. USD, EUR, GBP).', max_length=5, unique=True)),
                ('symbol', models.CharField(help_text='Symbol (e.g. $, €, £).', max_length=5)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, help_text='Rate relative to USD. Use 1.0 for USD itself.', max_digits=15)),
                ('is_default', models.BooleanField(default=False, help_text='Site-wide default. Only one currency can be default.')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
                'ordering': ['-is_default', 'code'],
            },
        ),
    ]
