"""
Django settings for storybook project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os
from django.contrib.messages import constants as messages
from django.db import connections
from django.db.utils import OperationalError
import sys
from decouple import config



try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass


# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

SECRET_KEY = env('SECRET_KEY')

# DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'
DEBUG = True
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

CSRF_TRUSTED_ORIGINS = [
    'https://gw.cgate.tech',
    'https://gw-test.cgate.tech',
    'https://littlestorybox.com',
    'https://www.littlestorybox.com',
    'https://littlestorybox.supporthives.com',
    'https://magicstorycorner.supporthives.com',
]

# Tell Django it's behind an HTTPS-terminating reverse proxy (nginx).
# This makes request.build_absolute_uri() return https:// URLs.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

PLAYWRIGHT_BROWSERS_PATH = 0

if PLAYWRIGHT_BROWSERS_PATH == 0:
    os.environ["PLAYWRIGHT_BROWSERS_PATH"] = "0"


APPEND_SLASH = True


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!


# SECURITY WARNING: keep the secret key used in production secret!





# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    'accounts.apps.AccountsConfig',
    'stories.apps.StoriesConfig',
    'products.apps.ProductsConfig',
    'payments.apps.PaymentsConfig',
    'pages.apps.PagesConfig',
    'legals.apps.LegalsConfig',
    'logs.apps.LogsConfig',
    'demos.apps.DemosConfig',
    'import_export',
    'django.contrib.humanize',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}


ROOT_URLCONF = 'storybook.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.loggedin_user',
                'storybook.context_processors.white_header',
                'storybook.context_processors.story_header',
                'storybook.context_processors.get_active_website',
                'storybook.context_processors.model_counts',
                'logs.context_processors.logs',
                'logs.context_processors.today_logs',
                "accounts.context_processors.global_currencies",
            ],
        },
    },
]

WSGI_APPLICATION = 'storybook.wsgi.application'


DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB
SESSION_EXPIRE_AT_BROWSER_CLOSE = True





# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PyMySQL locally
USE_PYMYSQL = os.getenv("USE_PYMYSQL", "true").lower() == "true"

if USE_PYMYSQL:
    import pymysql
    pymysql.install_as_MySQLdb()
    backend_msg = "Using PyMySQL as MySQL backend"
else:
    backend_msg = "Using MySQLClient as MySQL backend"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# AUTH_USER_MODEL = 'accounts.User'


# Email configuration
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "LITTLESTORYBOX <support@littlestorybox.com>")
ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "support@littlestorybox.com")


#testing
RECAPTCHA_PUBLIC_KEY = "6LdG9hMsAAAAAF9WLnInxm4Q-9vn7Z-WiHanx1AW"
RECAPTCHA_PRIVATE_KEY = "6LdG9hMsAAAAACCXKRH0qsSPDYQunMSPRULbqKHF"


#live
# RECAPTCHA_PUBLIC_KEY = "6LcbuO0rAAAAAEIec_HnPO86lEUGILHeJ34Qjo4C"
# RECAPTCHA_PRIVATE_KEY = "6LcbuO0rAAAAADmWFG834ciaZmGF_k5TfYdomlLA"





#payment gateway testing
# CITIPAY_MERCHANT_NAME = "WSCalligraphiiMaster" 
# CITIPAY_SECRET_KEY = "Y*a34rA$J_q76W!z"
# CITIPAY_API_URL = "https://gw.cgate.tech/orion/api"
# CITIPAY_PAYMENT_URL = "https://gw.cgate.tech/orion/hosted/Payment.aspx"


#payment gateway live
CITIPAY_MERCHANT_NAME = "WSLittleStoryBoxMaster" 
CITIPAY_SECRET_KEY = "Tp5!_Rm62i-YW$3a"
CITIPAY_API_URL = "https://gw.cgate.tech/orion/api"
CITIPAY_PAYMENT_URL = "https://gw.cgate.tech/orion/hosted/Payment.aspx"




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

# TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # same for local + server

STATIC_ROOT = BASE_DIR / 'staticfiles'


# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}

