# Generated by Django 5.2.7 on 2025-11-20 06:31

import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storybook',
            name='char_desc',
            field=models.TextField(blank=True, help_text='Description of the main character.', null=True),
        ),
        migrations.AddField(
            model_name='storybook',
            name='char_img',
            field=models.ImageField(blank=True, help_text='Reference image of the main character.', null=True, upload_to=stories.models.storybook_character_image_upload_path),
        ),
        migrations.AddField(
            model_name='storybook',
            name='char_name',
            field=models.CharField(blank=True, help_text="Main character's name.", max_length=100, null=True),
        ),
    ]
