# Generated by Django 5.2.7 on 2025-12-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_storybook_char_desc_storybook_char_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storybookpage',
            name='prompt',
            field=models.TextField(blank=True, help_text='Prompt used for generating the image of this page.', null=True),
        ),
    ]
