# Generated by Django 5.2.7 on 2025-12-19 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_storybookpage_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='storybook',
            index=models.Index(fields=['user', 'is_active', 'status', '-created_at'], name='user_active_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='storybook',
            index=models.Index(fields=['user', 'is_active', 'status', 'tokens', 'id'], name='user_active_status_tokens_idx'),
        ),
        migrations.AddIndex(
            model_name='storybook',
            index=models.Index(fields=['user', 'is_active', 'status', '-tokens', 'id'], name='user_active_tokens_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='storybook',
            index=models.Index(fields=['user', 'is_active', 'status', '-created_at', 'id'], name='user_active_created_id_idx'),
        ),
        migrations.AddIndex(
            model_name='storybook',
            index=models.Index(fields=['user', 'status'], name='user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='storybook',
            index=models.Index(fields=['status'], name='story_status_idx'),
        ),
        migrations.AddIndex(
            model_name='storybook',
            index=models.Index(fields=['title'], name='story_title_idx'),
        ),
        migrations.AddIndex(
            model_name='storybook',
            index=models.Index(fields=['slug'], name='story_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='storybook',
            index=models.Index(fields=['user', 'agegroup', 'is_active', 'status'], name='user_agegroup_active_idx'),
        ),
        migrations.AddIndex(
            model_name='storybook',
            index=models.Index(fields=['user', 'plot', 'is_active', 'status'], name='user_plot_active_idx'),
        ),
        migrations.AddIndex(
            model_name='storybook',
            index=models.Index(fields=['user', 'theme', 'is_active', 'status'], name='user_theme_active_idx'),
        ),
        migrations.AddIndex(
            model_name='storybook',
            index=models.Index(fields=['user', 'narrator', 'is_active', 'status'], name='user_narrator_active_idx'),
        ),
        migrations.AddIndex(
            model_name='storybook',
            index=models.Index(fields=['user', 'imagestyle', 'is_active', 'status'], name='user_imagestyle_active_idx'),
        ),
        migrations.AddIndex(
            model_name='storybookpage',
            index=models.Index(fields=['book', 'page'], name='story_book_page_idx'),
        ),
        migrations.AddIndex(
            model_name='storybookpage',
            index=models.Index(fields=['book', 'image'], name='story_book_image_idx'),
        ),
    ]
