# Generated by Django 5.2.7 on 2025-11-15 08:46

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_picture_path)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender identity', max_length=10, null=True)),
                ('bio', models.TextField(blank=True, help_text='Short bio or description about the user', null=True)),
                ('profession', models.CharField(blank=True, help_text='User’s profession or role', max_length=100, null=True)),
                ('wallet', models.PositiveIntegerField(default=0, help_text='Current token balance')),
                ('line_1', models.CharField(blank=True, help_text='Primary street address or house number', max_length=255, null=True)),
                ('line_2', models.CharField(blank=True, help_text='Apartment, suite, or additional address info', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City or town name', max_length=100, null=True)),
                ('postal', models.CharField(blank=True, help_text='Postal or ZIP code', max_length=20, null=True)),
                ('state', models.CharField(blank=True, help_text='State or province name', max_length=100, null=True)),
                ('country', models.CharField(blank=True, help_text='Country name', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('recharge', 'Recharge'), ('deduct', 'Deduct')], default='recharge', help_text='Last wallet action type', max_length=10)),
                ('amount', models.PositiveIntegerField(default=0, help_text='Token amount that was recharged or deducted in the last transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
    ]
