# Generated by Django 5.2.7 on 2025-11-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_token',
            field=models.CharField(blank=True, help_text="Unique token used for verifying the user's email address", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="Indicates whether the user's email has been verified"),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the email was verified', null=True),
        ),
    ]
