# Generated by Django 5.2.7 on 2025-12-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dailyclaim_referralcode_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='message',
            field=models.CharField(blank=True, help_text='Optional message or note for this transaction', max_length=255, null=True),
        ),
    ]
