# Generated by Django 5.2.7 on 2025-12-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_wallet_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.PositiveIntegerField(default=0, help_text='Current token balance'),
        ),
    ]
