# Generated by Django 5.2.7 on 2026-04-21 06:31

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_wallet_balance'),
        ('payments', '0004_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.ForeignKey(default=accounts.models.get_default_currency, on_delete=django.db.models.deletion.CASCADE, to='payments.currency'),
        ),
    ]
