# Generated by Django 5.2.7 on 2025-11-22 04:44

import legals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.CharField(help_text='Enter the name of the company.', max_length=255, unique=True)),
                ('domain', models.CharField(help_text='Enter the name of the domain (e.g. www.littlestorybook.com).', max_length=255)),
                ('website', models.URLField(help_text='Enter the website domain (e.g., https://littlestorybook.com).', max_length=500)),
                ('email', models.EmailField(blank=True, help_text='Enter the contact email address.', max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, help_text='Enter the contact mobile number (e.g., +1234567890).', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Enter the company or website address.', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Upload the company or website logo.', null=True, upload_to=legals.models.logo_upload_path)),
                ('header', models.ImageField(blank=True, help_text='Upload the header image for the website.', null=True, upload_to=legals.models.header_upload_path)),
                ('footer', models.ImageField(blank=True, help_text='Upload the footer image for the website.', null=True, upload_to=legals.models.footer_upload_path)),
                ('signature', models.ImageField(blank=True, help_text='Upload the signature image.', null=True, upload_to=legals.models.signature_upload_path)),
            ],
            options={
                'db_table': 'websites',
            },
        ),
    ]
