# Generated by Django 5.2.7 on 2025-12-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legals', '0002_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='api_key',
            field=models.CharField(blank=True, help_text='General API key', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='api_secret',
            field=models.CharField(blank=True, help_text='General API secret', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='Facebook Pixel ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics tracking ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='maintenance_message',
            field=models.TextField(blank=True, help_text='Maintenance mode message', null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Enable maintenance mode'),
        ),
        migrations.AddField(
            model_name='website',
            name='payment_gateway',
            field=models.CharField(blank=True, help_text='Payment gateway (e.g., Stripe, PayPal, Razorpay)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='payment_key',
            field=models.CharField(blank=True, help_text='Payment gateway public/publishable key', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='payment_secret',
            field=models.CharField(blank=True, help_text='Payment gateway secret key', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='recaptcha_secret_key',
            field=models.CharField(blank=True, help_text='Google reCAPTCHA secret key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='recaptcha_site_key',
            field=models.CharField(blank=True, help_text='Google reCAPTCHA site key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='sms_api_key',
            field=models.CharField(blank=True, help_text='SMS API key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='sms_api_secret',
            field=models.CharField(blank=True, help_text='SMS API secret', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='sms_provider',
            field=models.CharField(blank=True, help_text='SMS provider (e.g., Twilio)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='sms_sender_id',
            field=models.CharField(blank=True, help_text='SMS sender ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='SMTP host (e.g., smtp.gmail.com)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='SMTP password', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, help_text='SMTP port (e.g., 587)', null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS for SMTP'),
        ),
        migrations.AddField(
            model_name='website',
            name='smtp_username',
            field=models.CharField(blank=True, help_text='SMTP username/email', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='social_facebook',
            field=models.URLField(blank=True, help_text='Facebook page URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='social_instagram',
            field=models.URLField(blank=True, help_text='Instagram profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='social_linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='social_twitter',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='social_youtube',
            field=models.URLField(blank=True, help_text='YouTube channel URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='domain',
            field=models.CharField(help_text='Enter the name of the domain (e.g. www.littlestorybox.com).', max_length=255),
        ),
        migrations.AlterField(
            model_name='website',
            name='website',
            field=models.URLField(help_text='Enter the website domain (e.g., https://littlestorybox.com).', max_length=500),
        ),
    ]
