name: Deploy Staging

on:
  push:
    branches:
      - devtaiga

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/magicstorycorner
            source env/bin/activate
            git pull
            python3 manage.py collectstatic --noinput
            sudo systemctl restart gunicorn