# Generated by Django 5.2.7 on 2025-11-15 08:46

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='Title of the Product Book.', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug for the Product Book.', max_length=220, null=True)),
                ('description', models.TextField(blank=True, help_text='Short description of the Product Book.')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price of the Product Book.', max_digits=10)),
                ('currency', models.CharField(default='$', help_text='Currency symbol used for pricing.', max_length=5)),
                ('prompt', models.TextField(blank=True, help_text='Prompt used for generating the Product Book.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Cover image of the Product Book.', null=True, upload_to=products.models.productbook_image_upload_path)),
                ('pdf', models.FileField(blank=True, help_text='PDF version of the Product Book.', null=True, upload_to=products.models.productbook_pdf_upload_path)),
                ('storyend', models.TextField(blank=True, help_text='Optional custom ending for the story.', null=True)),
                ('tokens', models.PositiveIntegerField(default=0, help_text='Tokens required to unlock this Product Book.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Book generation status.', max_length=20)),
                ('agegroup', models.ForeignKey(blank=True, help_text='Target age group.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.childagerange')),
                ('imagestyle', models.ForeignKey(blank=True, help_text='Preferred illustration style.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.imagestyle')),
                ('language', models.ForeignKey(blank=True, help_text='Language of the story.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.languageoption')),
                ('length', models.ForeignKey(blank=True, help_text='Approximate story length.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.storylength')),
                ('narrator', models.ForeignKey(blank=True, help_text='Narrator voice for audio playback.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.narratorvoice')),
                ('plot', models.ForeignKey(blank=True, help_text='Plot type of the story.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.storyplot')),
                ('setting', models.ForeignKey(blank=True, help_text='Main setting of the story.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.storysetting')),
                ('theme', models.ForeignKey(blank=True, help_text='Theme of the story.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.storytheme')),
                ('tone', models.ForeignKey(blank=True, help_text='Tone or mood of the story.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.storytone')),
            ],
            options={
                'db_table': 'product_books',
            },
        ),
        migrations.CreateModel(
            name='ProductBookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.PositiveIntegerField(help_text='Page number inside the Product Book.')),
                ('text', models.TextField(help_text='Text content of the page.')),
                ('image', models.ImageField(blank=True, help_text='Optional image for this page.', null=True, upload_to=products.models.productbook_page_image_upload_path)),
                ('audio', models.FileField(blank=True, help_text='Optional audio narration for this page.', null=True, upload_to=products.models.productbook_page_audio_upload_path)),
                ('book', models.ForeignKey(help_text='Product Book this page belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='products.productbook')),
            ],
            options={
                'db_table': 'product_book_pages',
                'ordering': ['page'],
                'unique_together': {('book', 'page')},
            },
        ),
        migrations.CreateModel(
            name='ProductBookPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='products.productbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_productbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_book_purchases',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
