# Generated by Django 5.2.7 on 2025-12-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productbook_char_desc_productbook_char_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbookpage',
            name='prompt',
            field=models.TextField(blank=True, help_text='Prompt used for generating the image of this page.', null=True),
        ),
    ]
