# Generated by Django 5.2.7 on 2025-12-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productbookpage_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chars_per_page', models.IntegerField(default=400, help_text='Characters allowed per page.')),
                ('max_pages', models.IntegerField(default=25, help_text='Maximum story pages.')),
                ('img_retries', models.IntegerField(default=3, help_text='Image generation retry count.')),
                ('tts_retries', models.IntegerField(default=3, help_text='TTS retry count.')),
                ('workers', models.IntegerField(default=10, help_text='Number of parallel workers.')),
                ('consistency_checks', models.IntegerField(default=3, help_text='How many characters (main + side) must stay visually consistent.')),
                ('story_retries', models.IntegerField(default=3, help_text='Story generation retry attempts.')),
                ('min_story_len', models.IntegerField(default=75, help_text='Minimum percentage of required story length before retry.')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
