# Generated by Django 5.2.7 on 2025-12-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='admin', help_text='Configuration for admin or user side.', max_length=20),
        ),
    ]
