# Generated by Django 5.2.7 on 2025-12-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_configuration_type'),
        ('stories', '0004_storybook_user_active_status_created_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productbook',
            index=models.Index(fields=['is_active', 'status', '-created_at'], name='active_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='productbook',
            index=models.Index(fields=['is_active', 'status', 'tokens', 'id'], name='active_status_tokens_idx'),
        ),
        migrations.AddIndex(
            model_name='productbook',
            index=models.Index(fields=['is_active', 'status', '-tokens', 'id'], name='active_status_tokens_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='productbook',
            index=models.Index(fields=['is_active', 'status', '-created_at', 'id'], name='active_status_created_id_idx'),
        ),
        migrations.AddIndex(
            model_name='productbook',
            index=models.Index(fields=['status'], name='status_idx'),
        ),
        migrations.AddIndex(
            model_name='productbook',
            index=models.Index(fields=['title'], name='title_idx'),
        ),
        migrations.AddIndex(
            model_name='productbook',
            index=models.Index(fields=['agegroup', 'is_active', 'status'], name='agegroup_active_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productbook',
            index=models.Index(fields=['plot', 'is_active', 'status'], name='plot_active_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productbook',
            index=models.Index(fields=['theme', 'is_active', 'status'], name='theme_active_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productbook',
            index=models.Index(fields=['narrator', 'is_active', 'status'], name='narrator_active_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productbook',
            index=models.Index(fields=['imagestyle', 'is_active', 'status'], name='imagestyle_active_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productbookpage',
            index=models.Index(fields=['book', 'page'], name='book_page_idx'),
        ),
        migrations.AddIndex(
            model_name='productbookpage',
            index=models.Index(fields=['book', 'image'], name='book_image_idx'),
        ),
    ]
