# Generated by Django 5.2.7 on 2026-03-12 06:05

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productbook_active_status_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbook',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated compressed thumbnail from cover image.', null=True, upload_to=products.models.productbook_thumbnail_upload_path),
        ),
    ]
